name: clean_env
channels:
  - conda-forge
  - defaults
  - nvidia
  - pytorch
dependencies:
  # - python=3.10  # You may want to specify a Python version
  - conda-forge::torchdiffeq
  - graphviz
  - grpcio=1.62.1
  - matplotlib
  - mpi4py=4.0.0
  - networkx
  - numpy
  - opt_einsum
  #- paho-mqtt=2.1.0
  - paho-mqtt
  - pillow=10.4.0
  # - protobuf=5.28.2
  - protobuf
  # - ptflops=0.7.4
  - ptflops
  - pyyaml
  # - ruamel.base=1.0.0
  - ruamel.yaml
  - scikit-learn
  - scipy
  - seaborn
  #- wandb=0.18.3
  - wandb
  - pip
  - pip:
    - FedML

# Uncomment the following lines if you want to include specific torch versions
# - pytorch=2.2.1
# - torchvision=0.17.1
# - cudatoolkit=11.1  # Adjust based on your CUDA version