# device: "cuda" | "cpu"
device: cuda
debug: true

# distributed networks
# users:            number of users
rounds: 30
users: 300

# Selects 20 per round
part_rate: 1.0 #0.07

lr: 0.01
# Hard coded based on training data set size. For example, 60000 fashion mnist images/300 users = 200 batch size
# I think this only applies to 
local_batch_size: 200
cluster_size: 5

# Whether or not weights should be initialized to the same value for each client originally
same_init: true

loss: "ce"

taus:
- 100
- 200
- 300 
- 400
- 500
- 600
- 700
- 800
- 900
- 1000
- 1500
- 2000

# Dataset configurations
train_data_dir: data/fmnist/train.dat
test_data_dir:  data/fmnist/test.dat

# I think user_with_data is the file that contains the user data parsed into non IID segments already
# This file is alpha0.1 

#user_with_data: "data/user_with_data/fmnist300/a0.1/user_dataidx_map_0.10_0.dat"
#iid: false

user_with_data: ""
iid: true

datapoint_size:
- 28
- 28
channels: 1
label_size: 10

# Log and record configurations
record_dir:  ../{}.dat
log_level:   "INFO"
log_file:    "./train.log"

model: "mlp"
full_weight_dir: ""