# device: "cuda" | "cpu"
device: cuda
debug: true


# users:         
rounds: 1
users: 300

# DFedAvgM hyperparameters
# Like client fraction C in FedAvg. Needs to be 1 for decentralized methods
part_rate: 1
# E in FedAvg
local_update_steps: 20
lr: 0.01
sgd_batch_size: 50
momentum: 0.9

verbose: false

record_path:

topology: "regular"
static: false

graph_name:
p:
d: 5

# Number of datapoints per user
local_batch_size: 200

# Whether or not weights should be initialized to the same value for each client originally
same_init: true

loss: "ce"

# Dataset configurations
# train_data_dir: ../../../data/fmnist/train.dat
# test_data_dir: ../../../data/fmnist/test.dat


# train_data_dir: ../../../data/emnist/digits/train.dat
# test_data_dir: ../../../data/emnist/digits/test.dat


# For IID data
# user_with_data: ""
# iid: true

# user_with_data is the file that contains the user data parsed into non IID segments already

# user_with_data: ""
# iid: false

# MNIST
train_data_dir: ../../../data/mnist/train.dat
test_data_dir: ../../../data/mnist/test.dat

user_with_data: "../../../data/user_with_data/mnist300/a0.5/user_dataidx_map_0.50_0.dat"
iid: false

# user_with_data: "../../../data/user_with_data/emnist/digits/user_dataidx_map_0.dat"
# iid: false

# user_with_data: "../../../data/user_with_data/fmnist300/a0.1/user_dataidx_map_0.10_0.dat"
# iid: false


datapoint_size:
- 28
- 28
channels: 1
label_size: 10

# Log and record configurations
record_dir: "./records/{}.dat"
log_level: "INFO"
log_file: "./records/train.log"

model: "mlp"
full_weight_dir: ""

